In [1]:
import torch as tc
tc.randn(3, 4)
#在均值为0,标准差为1的高斯分布（正态分布）中随机取样

tensor([[ 1.4334,  0.5573, -0.3414, -0.2880],
        [-1.0925, -0.0240,  0.5470,  1.2926],
        [-1.7627, -0.5275,  0.1691,  0.6558]])

In [2]:
x = tc.tensor([1.0, 2, 4, 8])
tc.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [3]:
#张量链接
X = tc.arange(12,dtype=tc.float32).reshape(3, 4)
Y = tc.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y, tc.cat((X, Y), dim=0), tc.cat((X, Y), dim=1)
#分别显示第行合并和列合并

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [4]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

以下是稍微难记一点的切片和索引：

In [5]:
X, X[-1], X[1:3]
#分别是选择最后一个元素和选择第二个和第三个元素，注意区间表示是左闭右开

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [6]:
X[1, 2] = 9
X
#把第二行第三列的元素变成9

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
X[0:2, :] = 12
X
#把第一行到第二行的每一列的元素变成

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [8]:
X[0:3, 0:2] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 10., 11.]])

对象的转换：

In [9]:
A = X.numpy()
B = tc.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [10]:
A, B

(array([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 10., 11.]], dtype=float32),
 tensor([[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [12., 12., 10., 11.]]))

In [11]:
#大小为1的张量和标量的互相转化
a = tc.tensor([3.5])
a, a.item(), float(a), int(a)
#item()函数是torch内用于转型的函数

(tensor([3.5000]), 3.5, 3.5, 3)

## 数据处理

In [12]:
import os
#os模块提供与操作系统相互交互的功能

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
os.makedirs(os.path.join('..','comfirm_example'), exist_ok=True)
#使用该内函数构造路径'../data'，表示当前目录的上一级目录下的data文件夹
#外函数创建该路径下的目录，如果目录已存在且exist_ok=True,就不报错
#这一步是在创建文件夹
data_file = os.path.join('..', 'data', 'house_tiny.csv')
ce = os.path.join('..', 'comfirm_example', 'test.csv')#实际这一步我们已经创建好了文件，但是因为还没写，就是空文件，不显示
#构造路径'../data/house_tiny.csv',并赋值给该变量
with open(data_file, 'w') as f:
    #以写模式'w'打开文件data_file文件，并使用with语句保证文件在操作后可以顺利关闭
    f.write('NumRooms,Alley,Price\n')
    #给文件写入表头
    f.write('NA,Pave,127500\n')
    #向文件写入一行数据
    f.write('2,NA,106000\n')
    f.write('3,NA,178100\n')
    f.write('NA,NA,140000\n')
with open(ce, 'w') as c:
    c.write('i, you, he\n')
    c.write('ZMY, LJX, Nobody\n')

In [13]:
import pandas as pd
#pandas是数据处理和分析的库


data = pd.read_csv(data_file)
name = pd.read_csv(ce)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       3.0   NaN  178100
3       NaN   NaN  140000

知识解释：
1. csv文件是常见的数据储存格式，用于储存***表格数据*** ，每一行代表一条记录，字段之间用逗号隔开
2. 'w'是文件打开方式的一种，即写模式，如果文件已经存在'w'模式会清除文件内容并从头开始写；如果文件不存在，则会创造新的文件
3. 一层目录可以理解为一层文件夹
4. 我们通过这样程序在系统的jupyter文件夹里创建了一个data文件夹，并在这个文件夹里创建以一个csv文件

In [14]:
name

     i   you       he
0  ZMY   LJX   Nobody

缺失值处理：

In [15]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
#就是把表格中第一列和第二列的元素全部提取出来归为一个大类，特征；第三列提取出来归为标签（输出）
#其中的iloc函数是列表索引函数
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       2.5  Pave
1       2.0   NaN
2       3.0   NaN
3       2.5   NaN

In [16]:
#显然这种方法对string是不起作用的，用以下的归类方法
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

   NumRooms  Alley_Pave  Alley_nan
0       2.5           1          0
1       2.0           0          1
2       3.0           0          1
3       2.5           0          1

解释：
1. 通过pd.get_dummies()函数进行字符串的独热编码，我们通过Ture告知程序我们需要对NaN缺失值单独生成一个哑变量列
2. 通过引入独热编码函数get_dummies进行独热编码，独热编码函数的参数有多种，dummy_na是其中一种（默认是Fales）,其他的我暂时没有了解了

In [17]:
X, y = tc.tensor(inputs.values, dtype=tc.float32), tc.tensor(outputs.values)
X, y
#向量化表格数据

(tensor([[2.5000, 1.0000, 0.0000],
         [2.0000, 0.0000, 1.0000],
         [3.0000, 0.0000, 1.0000],
         [2.5000, 0.0000, 1.0000]]),
 tensor([127500, 106000, 178100, 140000]))